### ISSUE TITLE
无法启用插件

### ISSUE THREAD

**Issue by noviachen** [GoldJohnKing/ParsedownExtra-for-Typecho#1]
提示下面这样的错误信息
Parse error: syntax error, unexpected 'ParsedownExtra' (T_STRING) in /usr/plugins/ParsedownExtra/Plugin.php on line 41

在下面的链接里发现另外一个 Markdown 插件也出现过这样的问题，不知我也是因为 php 的版本造成的，我用的是 5.4
[https://github.com/kokororin/typecho-plugin-Parsedown/issues/1](https://github.com/kokororin/typecho-plugin-Parsedown/issues/1)

**Comment by sunjx888** [comment]
同问Parse error: syntax error, unexpected 'ParsedownExtra' (T_STRING) in /www/wwwroot/Blog/usr/plugins/ParsedownExtra/Plugin.php on line 41，PHP版本5.4

**Comment by GoldJohnKing** [comment]
这插件发完了我也就没看了……对于迟到的回复深表抱歉。

本解析器不支持 PHP 5.2 版本，我也没用过这个版本的PHP所以也没测试过……

另外补充一点，建议使用 PHP 5.5 版本或者 PHP 7。

**Comment by SportPlusX** [comment]
PHP 7 无法启用

```
syntax error, unexpected 'ParsedownExtra' (T_STRING)
```

**Comment by GoldJohnKing** [comment]
@bpplpp 请检查是否以将插件文件夹重命名为“ParsedownExtra”。

**Comment by SportPlusX** [comment]
@GoldJohnKing 看来是不兼容了
